const types = {
  GET_TODO: "GET_TODO",
  GET_TODO_SUCCESS: "GET_TODO_SUCCESS",
  GET_TODO_FAILED: "GET_TODO_FAILED",

  POST_TODO: "POST_TODO",
  POST_TODO_SUCCESS: "POST_TODO_SUCCESS",
  POST_TODO_FAILED: "POST_TODO_FAILED",

  DELETE_TODO: "DELETE_TODO",
  DELETE_TODO_SUCCESS: "DELETE_TODO_SUCCESS",
  DELETE_TODO_FAILED: "DELETE_TODO_FAILED",

  PUT_TODO: "PUT_TODO",
  PUT_TODO_SUCCESS: "PUT_TODO_SUCCESS",
  PUT_TODO_FAILED: "PUT_TODO_FAILED",
};

export default types;
